POST http://localhost:8080/microchip/lifecycle/command/ASSOCIATE_MICROCHIP
Content-Type: application/json

{
  "petId": 131,
   "action": "ASSOCIATE_MICROCHIP",
   "chipNumber": "620003394",
   "eventInfo": {
     "user": {"id": 324, "email": "dbustamante69@gmail.com"},
     "sourceIp": "192.168.1.23",
     "browser": "Chrome 911",
     "device": "Mac OS 2",
     "os": "Mac OS",
     "properties": {"extra1": "ggt", "extra2": 5556}
   }
}

###

POST http://localhost:8080/microchip/lifecycle/command/ACTIVATE_MICROCHIP
Content-Type: application/json

{
  "petId": 131,
   "action": "ACTIVATE_MICROCHIP",
   "chipNumber": "620003394",
   "eventInfo": {
     "user": {"id": 324, "email": "dbustamante69@gmail.com"},
     "sourceIp": "192.168.1.23",
     "browser": "Chrome 911",
     "device": "Mac OS 2",
     "os": "Mac OS",
     "properties": {"extra1": "ggt", "extra2": 5556}
   }
}


###

POST http://localhost:8080/microchip/lifecycle/command/ACTIVATE_TAG
Content-Type: application/json

{
  "petId": 3819,
   "action": "ACTIVATE_TAG",
   "chipNumber": "NPLHW3PK",
   "eventInfo": {
     "user": {"id": 324, "email": "dbustamante69@gmail.com"},
     "sourceIp": "192.168.1.23",
     "browser": "Chrome 911",
     "device": "Mac OS 2",
     "os": "Mac OS",
     "properties": {"extra1": "ggt", "extra2": 5556}
   }
}

###

POST http://localhost:8080/microchip/lifecycle/command/DELETE_MICROCHIP
Content-Type: application/json

{
  "petId": 131,
   "action": "DELETE_MICROCHIP",
   "chipNumber": "620003394",
   "eventInfo": {
     "user": {"id": 324, "email": "dbustamante69@gmail.com"},
     "sourceIp": "192.168.1.23",
     "browser": "Chrome 911",
     "device": "Mac OS 2",
     "os": "Mac OS",
     "properties": {"extra1": "ggt", "extra2": 5556}
   }
}

###

POST http://localhost:8080/microchip/lifecycle/command/CANCEL_DELETE_MICROCHIP
Content-Type: application/json

{
  "petId": 131,
   "action": "CANCEL_DELETE_MICROCHIP",
   "chipNumber": "620003394",
   "eventInfo": {
     "user": {"id": 324, "email": "dbustamante69@gmail.com"},
     "sourceIp": "192.168.1.23",
     "browser": "Chrome 911",
     "device": "Mac OS 2",
     "os": "Mac OS",
     "properties": {"extra1": "ggt", "extra2": 5556}
   }
}


###

GET http://localhost:8080/microchip/620000002

###

GET http://localhost:8080/microchip/pet/131

###

POST http://localhost:8080/microchip/lifecycle/commands
Content-Type: application/json

[{
  "petId": 160,
   "action": "ASSOCIATE_MICROCHIP",
   "chipNumber": "620000899",
   "eventInfo": {
     "user": {"id": 324, "email": "dbustamante69@gmail.com"},
     "sourceIp": "192.168.1.23",
     "browser": "Chrome 911",
     "device": "Mac OS 2",
     "os": "Mac OS",
     "properties": {"extra1": "ggt", "extra2": 5556}
   }
},{
    "petId": null,
     "action": "ACTIVATE_MICROCHIP",
     "chipNumber": "620000799",
     "eventInfo": {
       "user": {"id": 324, "email": "dbustamante69@gmail.com"},
       "sourceIp": "192.168.1.23",
       "browser": "Chrome 911",
       "device": "Mac OS 2",
       "os": "Mac OS",
       "properties": {"extra1": "ggt", "extra2": 5556}
     }
  }]

###

GET http://localhost:8080/ids/all

###

GET http://localhost:8080/ids/latest

###

GET http://localhost:8080/ids/S5SK6QPG

###



GET http://localhost:8080/ids/latest/2

###

POST http://localhost:8080/tags/generate/16

###

GET http://localhost:8080/tags/grids/lasts

###

GET http://localhost:8080/tags/all

###

GET http://localhost:8080/tags/for/grid/b350d176-5ade-449a-bdf7-488f93cc380a

###

PUT http://localhost:8080/tags/grid/pdfs
Content-Type: application/json

{
   "id": "b350d176-5ade-449a-bdf7-488f93cc380a",
   "url": "http://urltest1",
   "printUrl": "http://urltest2"
}

###

POST http://localhost:8080/leads/owner
Content-Type: application/json

{
    "code" : "V3QUPFY2",
    "email":"dbustamante69@gmail.com",
    "name":"Daniel Bustamante",
    "phoneNumber":"3044613258"
}

###

###

GET http://localhost:8080/ids/active/V3QUPFY2

###

GET http://localhost:8080/microchip/620003394

###

###

GET http://localhost:8080/ids/TAG/pet/3819

###

POST http://localhost:8080/alert/command/CREATE_ALERT
Content-Type: application/json

{
   "action": "CREATE_ALERT",
   "alertInfo": {
     "upetId": "620003394"
   },
   "eventInfo": {
     "user": {"id": 324, "email": "dbustamante69@gmail.com"},
     "sourceIp": "192.168.1.23",
     "browser": "Chrome 911",
     "device": "Mac OS 2",
     "os": "Mac OS",
     "properties": {"extra1": "ggt", "extra2": 5556}
   }
}

###

POST http://localhost:8080/alert/command/ADD_ADDRESS
Content-Type: application/json

{
   "action": "ADD_ADDRESS",
   "alertInfo": {
     "alertId" : "2ac82bc6-7ec0-444b-b014-0332cd81b74b",
     "placeId": "ADDF3444FFD"
   },
   "eventInfo": {
     "user": {"id": 324, "email": "dbustamante69@gmail.com"},
     "sourceIp": "192.168.1.23",
     "browser": "Chrome 911",
     "device": "Mac OS 2",
     "os": "Mac OS",
     "properties": {"extra1": "ggt", "extra2": 5556}
   }
}

###

POST http://localhost:8080/alert/command/ADD_FINDER_NAME
Content-Type: application/json

{
   "action": "ADD_FINDER_NAME",
   "alertInfo": {
     "alertId" : "2ac82bc6-7ec0-444b-b014-0332cd81b74b",
     "finderName": "Daniel Bustamante"
   },
   "eventInfo": {
     "user": {"id": 324, "email": "dbustamante69@gmail.com"},
     "sourceIp": "192.168.1.23",
     "browser": "Chrome 911",
     "device": "Mac OS 2",
     "os": "Mac OS",
     "properties": {"extra1": "ggt", "extra2": 5556}
   }
}

###

POST http://localhost:8080/alert/command/ADD_PHONE
Content-Type: application/json

{
   "action": "ADD_PHONE",
   "alertInfo": {
     "alertId" : "2ac82bc6-7ec0-444b-b014-0332cd81b74b",
     "phone": "3044613258"
   },
   "eventInfo": {
     "user": {"id": 324, "email": "dbustamante69@gmail.com"},
     "sourceIp": "192.168.1.23",
     "browser": "Chrome 911",
     "device": "Mac OS 2",
     "os": "Mac OS",
     "properties": {"extra1": "ggt", "extra2": 5556}
   }
}

###

POST http://localhost:8080/alert/command/ADD_COORDINATES
Content-Type: application/json

{
   "action": "ADD_COORDINATES",
   "alertInfo": {
     "alertId" : "2ac82bc6-7ec0-444b-b014-0332cd81b74b",
     "latitude": "6.151705",
     "longitude": "-75.614838"
   },
   "eventInfo": {
     "user": {"id": 324, "email": "dbustamante69@gmail.com"},
     "sourceIp": "192.168.1.23",
     "browser": "Chrome 911",
     "device": "Mac OS 2",
     "os": "Mac OS",
     "properties": {"extra1": "ggt", "extra2": 5556}
   }
}

###

